version: '3.8'
services:
  dev:
    image: postgres:13
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: tikitu@123
      POSTGRES_DB: tikitu
    networks:
      - tikitu
networks:
  tikitu: